import { Platform, StyleSheet } from 'react-native';
import { SpreadsCategory } from 'shared/api';
import { COLORS, getColorOpacity } from 'shared/themes';
import { WEB_HOVER_TRANSITION } from './web/hoverTransition';

export const SPREAD_CATEGORY_ACCENT: Record<SpreadsCategory, string> = {
  [SpreadsCategory.Simple]: COLORS.Primary,
  [SpreadsCategory.Thematic]: COLORS.Secondary,
  [SpreadsCategory.Universal]: COLORS.Accent,
  [SpreadsCategory.SelfDevelopment]: COLORS.Info500,
  [SpreadsCategory.Choice]: COLORS.Warning500,
};

export const spreadInnerStyles = StyleSheet.create({
  glassPanel: {
    backgroundColor: getColorOpacity(COLORS.Background2, 92),
    borderRadius: 20,
    borderWidth: 1,
    borderColor: getColorOpacity(COLORS.SpbSky1, 28),
    padding: 16,
    overflow: 'visible',
    ...Platform.select({
      web: {
        boxShadow: '0 10px 28px rgba(0, 0, 0, 0.22)',
      },
      default: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.18,
        shadowRadius: 14,
        elevation: 8,
      },
    }),
  },
  sectionLabel: {
    color: getColorOpacity(COLORS.Content, 65),
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    fontSize: 11,
    lineHeight: 14,
    marginBottom: 10,
  },
  categoryChip: {
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
    borderWidth: 1,
  },
  categoryChipText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  heroShell: {
    width: '100%',
    height: 200,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: COLORS.SpbSky4,
    borderWidth: 1,
    borderColor: getColorOpacity(COLORS.SpbSky1, 28),
    ...Platform.select({
      web: {
        boxShadow: '0 12px 32px rgba(0, 0, 0, 0.28)',
      },
      default: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.22,
        shadowRadius: 16,
        elevation: 10,
      },
    }),
  },
  heroImage: {
    width: '100%',
    height: '100%',
    ...Platform.select({
      web: {
        objectFit: 'cover' as const,
        objectPosition: 'center center' as const,
      },
    }),
  },
  heroFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 120,
    pointerEvents: 'none',
  },
  descriptionText: {
    color: getColorOpacity(COLORS.Content, 78),
    lineHeight: 22,
    textAlign: 'center',
    maxWidth: 520,
    alignSelf: 'center',
  },
  altarZone: {
    width: '100%',
    maxWidth: 420,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    paddingVertical: 16,
    paddingHorizontal: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: getColorOpacity(COLORS.SpbSky1, 16),
    backgroundColor: getColorOpacity(COLORS.Background2, 35),
    overflow: 'visible',
    position: 'relative',
    marginHorizontal: 16,
    gap: 4,
  },
  altarGlow: {
    position: 'absolute',
    width: '120%',
    height: '90%',
    top: '5%',
    left: '-10%',
    borderRadius: 999,
    backgroundColor: getColorOpacity(COLORS.Primary, 3),
    pointerEvents: 'none',
  },
  altarHint: {
    marginTop: 4,
    textAlign: 'center',
    color: getColorOpacity(COLORS.Content, 50),
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.2,
  },
  completionPanel: {
    alignItems: 'center',
    padding: 24,
    gap: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: getColorOpacity(COLORS.Primary, 35),
    backgroundColor: getColorOpacity(COLORS.Background2, 90),
    marginHorizontal: 16,
    ...Platform.select({
      web: {
        boxShadow: '0 14px 36px rgba(246, 192, 27, 0.12)',
      },
      default: {},
    }),
  },
  completionTitle: {
    textAlign: 'center',
    color: COLORS.Primary,
    letterSpacing: 0.3,
  },
  stickyCta: {
    marginTop: 8,
    borderRadius: 32,
    height: 48,
    ...Platform.select({
      web: {
        boxShadow: '0 8px 24px rgba(246, 192, 27, 0.28)',
        ...WEB_HOVER_TRANSITION,
      },
      default: {},
    }),
  },
  timelineRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 12,
  },
  timelineRail: {
    width: 28,
    alignItems: 'center',
  },
  timelineLine: {
    position: 'absolute',
    top: 20,
    bottom: -16,
    width: 2,
    backgroundColor: getColorOpacity(COLORS.SpbSky1, 25),
    borderRadius: 1,
  },
  timelineDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 14,
    borderWidth: 2,
    zIndex: 1,
  },
  positionCard: {
    flex: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: getColorOpacity(COLORS.SpbSky1, 22),
    backgroundColor: getColorOpacity(COLORS.Background2, 85),
    marginBottom: 12,
    ...Platform.select({
      web: {
        ...WEB_HOVER_TRANSITION,
        cursor: 'default' as const,
      },
      default: {},
    }),
  },
  positionCardActive: {
    borderColor: getColorOpacity(COLORS.Primary, 55),
    backgroundColor: getColorOpacity(COLORS.Primary, 8),
  },
  positionCardDone: {
    borderColor: getColorOpacity(COLORS.Success500, 35),
  },
  positionCardPressable: Platform.select({
    web: { cursor: 'pointer' as const },
    default: {},
  }),
  positionIndex: {
    color: COLORS.SpbSky2,
    fontSize: 11,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  positionMeaning: {
    color: COLORS.Content,
    lineHeight: 20,
  },
  readingPositionLabel: {
    textAlign: 'center',
    color: getColorOpacity(COLORS.Content, 55),
    letterSpacing: 1.4,
    textTransform: 'uppercase',
    fontSize: 11,
    lineHeight: 14,
    marginBottom: 4,
  },
  readingPositionTitle: {
    textAlign: 'center',
    marginBottom: 4,
  },
  readingCardFrame: {
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: getColorOpacity(COLORS.Content, 45),
    borderRadius: 16,
    padding: 4,
    ...Platform.select({
      web: {
        boxShadow: '0 18px 34px rgba(0, 0, 0, 0.42)',
      },
      default: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.35,
        shadowRadius: 18,
        elevation: 12,
      },
    }),
  },
  summaryScroll: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: getColorOpacity(COLORS.Primary, 45),
    backgroundColor: getColorOpacity(COLORS.Background2, 96),
    padding: 20,
    gap: 12,
    overflow: 'hidden',
    position: 'relative',
  },
  summaryScrollAccent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: COLORS.Primary,
  },
  summaryText: {
    color: getColorOpacity(COLORS.Content, 88),
    lineHeight: 24,
    textAlign: 'left',
  },
  reversedChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: getColorOpacity(COLORS.Warning500, 40),
    backgroundColor: getColorOpacity(COLORS.Warning500, 12),
  },
  reversedChipText: {
    color: COLORS.Warning400,
    fontSize: 13,
    lineHeight: 16,
  },
});
