export default {};
export const Skia = {};
export const Canvas = () => null;
export const Path = () => null;
export const Fill = () => null;
export const Group = () => null;
export const Image = () => null;
export const useImage = () => null;
export const useFont = () => null;
export const useDerivedValue = (fn: any) => ({ value: fn() });
export const useSharedValue = (v: any) => ({ value: v });
export const rect = () => ({});
export const rrect = () => ({});
